{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scooter-rental.fullname" . }}-backup
  labels:
    {{- include "scooter-rental.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backup.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size | quote }}
  {{- if .Values.backup.persistence.storageClass }}
  storageClassName: {{ .Values.backup.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
