apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scooter-secrets-provider
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "SCOOTER_DB"
        objectType: "secretsmanager"
        jmesPath: 
            - path: "RDS_PASSWORD"
              objectAlias: "rds_password"
