{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  labels:
    {{- include "scooter-rental.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    region: {{ .Values.awsRegion }}
    objects: |
      - objectName: "{{ .Values.secretProviderClass.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range .Values.secretProviderClass.jmesPath }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
          {{- end }}
  secretObjects:
    - secretName: {{ include "scooter-rental.fullname" . }}-synced-secrets
      type: Opaque
      data:
        {{- range .Values.secretProviderClass.jmesPath }}
        - objectName: {{ .objectAlias }}
          key: {{ .objectAlias }}
        {{- end }}
{{- end -}}
